### PR TITLE
I economized 132 MB from my aplication

### PR DESCRIPTION
**Pull request by dotenorio**
Please, accept this simple modification for better world.

Thanks for your module, it's beautiful, and i love him.

❤️ ❤️

### CODE REVIEW

**Comment by dotenorio** [comment]
For example, see size of .exe in:

version v1.1.0 ~> 66 MB
version v1.1.1 ~> 31,2 MB

https://github.com/dotenorio/clipboard-manager-electron/releases

**Comment by arjun-g** [comment]
@dotenorio Thank you for the update. I didn't focus much on this project. Good to know this has been used in another project. I am merging the pull request.

**Comment by dotenorio** [comment]
Tks man..

**Comment by dotenorio** [comment]
Can u update on npm?

**Comment by arjun-g** [comment]
It is done as well. But for some reason npm portal is still showing me 1.1.0 as the latest. May be a cache problem. But npm install installs version 1.1.1

**Comment by dotenorio** [comment]
Ah ok, cool!

**Pull request merged**
